export const SET_BASE_URL = "SET_BASE_URL";
export const SET_TOKEN = "SET_TOKEN";
export const SET_SCAN_END_POINT = "SET_SCAN_END_POINT";
export const SET_GROUP_END_POINT = "SET_GROUP_END_POINT";
export const SET_GROUP_DETAIL_END_POINT = "SET_GROUP_DETAIL_END_POINT";
